### ISSUE TITLE
Notes doesn't create notes

### ISSUE THREAD

**Issue by gracerx** [cshdllr/Notes#1]
The concept of the plugin sounded great. Downloaded, unzipped, double clicked, successful install. In Sketch open  Plugins>Notes and when I click on the caret nothing. The keyboard : CMD-Y doesn't work. 

Sketch version: Version 41.2 (35397)
<img width="385" alt="screen shot 2016-12-01 at 1 35 15 pm" src="https://cloud.githubusercontent.com/assets/18198391/20813610/18cb51a0-b7cb-11e6-82b1-d102d69a1bd6.png">

**Comment by cshdllr** [comment]
hey @gracerx I just updated the plugin. Can you give it another try and let me know if you are still having trouble? FYI updated the shortcut to CMD + L.

**Comment by cshdllr** [comment]
Closing since the new release seems to have fixed this. Let me know if you are still having issues.
