### ISSUE TITLE
issue when selecting a note after its creation

### ISSUE THREAD

**Issue by alexksikes** [cshdllr/Notes#11]
First of all, congrats, this is actually the simplest but most effective way of annotating a sketch document. However, after an update of Sketch (don't know which one but it has been a while) the plugin creates a note which is no longer selectable, and so stuck in the middle of the screen. I hope this will get fixed soon. I am using cmd+drag as a quick fix for now. 

Sketch version: 46.1
Notes version: 2.0

Thank you.

**Comment by cshdllr** [comment]
Hey @alexksikes! That was a bug I was seeing a few months ago that should be fixed. Can you try downloading the plugin again and updating? 

The latest version is 2.1

**Comment by cshdllr** [comment]
I tested this and this issue should be fixed in 2.1. Let me know if you are still experiencing this after you update!
