### ISSUE TITLE
not working in v48.2?

### ISSUE THREAD

**Issue by renegadeoffvnk** [cshdllr/Notes#13]
plugin installs OK, but doesn't do anything (new note / hide notes / show notes / setting... nothing).

![image](https://user-images.githubusercontent.com/5641417/34536530-64556f64-f093-11e7-8976-aa40bf1c3f65.png)

sketch v48.2

**Comment by idoshavit** [comment]
Same here 😢   (48.2)

**Comment by felixdorner** [comment]
Same here

**Comment by hiliz** [comment]
Same here...

**Comment by kevin0606** [comment]
Same! I miss it :(

**Comment by datanatas** [comment]
+1

**Comment by patleeman** [comment]
Same

**Comment by chsWeb** [comment]
+1 not working.

**Comment by kigai** [comment]
@cshdllr Dude, please fix it we can't live without this plugin

**Comment by cherifzouein** [comment]
AGREED!

**Comment by cshdllr** [comment]
Sorry for being slow to address this! Will hopefully have a fix out this week once I can pinpoint what changed on Sketch's side.

**Comment by jwineman** [comment]
@cshdllr This plugin doesn't work for my use case!  When will you be rolling out support for encrypted sketch notes?!

**Comment by cshdllr** [comment]
Found the issues and Notes should now be working on Sketch v48.2. Apologies for the delay in getting the fix out. Please let me know if you are experiencing any other issues. 

Thanks for reporting @renegadeoffvnk, @idoshavit, @felixdorner, @hiliz, @kevin0606, @catogonzalez, @patleeman, @chsWeb, @kigai, @cherifzouein, @jwineman.

**Comment by idoshavit** [comment]
thank you thank you thank you 👍 🥇

**Comment by hiliz** [comment]
Yassss! Thanks <3
