### ISSUE TITLE
Can't create new notes

### ISSUE THREAD

**Issue by s-g-xie** [cshdllr/Notes#17]
When I create a new note, I can't seem to edit it in any way :(. I can use old notes; I just can't create working new ones; It's just an image I can't move or type in. Please help!

**Comment by asafbo** [comment]
Happens since the new version of Sketch 53

**Comment by quiqueciria** [comment]
I happend the same :(

**Comment by phon-os** [comment]
Hi, it actually works but the note is not selected right after creation and cannot be selected in the canvas - you need to use a little workaround. Select the note in the layers list and then in can be edited and even selected in the canvas.

But still, please fix it :)

**Comment by id1x** [comment]
Since this project seems to no longer be maintained, I built an alternative myself. Feel free to check it out: https://github.com/idriesalbender/notes-sketch-plugin

**Comment by cshdllr** [comment]
Hey everyone - Sorry for the radio silence here. (I stopped receiving notifications about this for some reason).

I will follow up here and get this fixed. In the future I plan to watch this more closely so something like this won't happen again.

**Comment by cshdllr** [comment]
Just added a fix for this in Notes 2.3. Please let me know if you are still having problems after you update!

Apologies for not addressing this sooner. #
