### ISSUE TITLE
Add identifier to manifest.json

### ISSUE THREAD

**Issue by mludowise** [cshdllr/Notes#4]
This plugin cannot automatically update in [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/) because it is missing an identifier in the manifest.json file. See http://developer.sketchapp.com/introduction/plugin-bundles/ for more info.

**Comment by cshdllr** [comment]
Added identifier

**Comment by mludowise** [comment]
Thank you!
