### ISSUE TITLE
can't select note without using command-drag

### ISSUE THREAD

**Issue by tayro** [cshdllr/Notes#5]
i love this plugin! it could change the world.

but, when i create a new note, i sometimes want to move it out of the way before entering text (or, enter some text, and then move it out of the way).

however, once i create a note, i can't select it! 
it's as if it doesn't exist - i can see it, but i can't touch it. 
i have to command-drag over it to select it, and then it starts to work as expected. weird right?

fixing this would be awesome, because in the meantime, when i command-drag to select my notes, i sometimes accidentally select layers that are behind the note, and it borks my design when i move it :(

**Comment by cshdllr** [comment]
Thanks for reporting @tayro. This seems to have happened with the latest sketch update./

 I've seen the problem you are talking about and am looking into how to fix it.

**Comment by cshdllr** [comment]
@tayro this should be fixed. Can you update the plugin and see if you are still having this problem?

fixed in #8
